#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar height=26 \
  y_offset=10 \
  notch_offset=-4 \
  position=top \
  blur_radius=30 \
  padding_right=10 \
  padding_left=10 \
  margin=20 \
  blur_radius=60 \
  corner_radius=4 \
  color="$BAR_COLOR"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Helvetica:Regular:14"
  label.font="Helvetica:Regular:14"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=5
  icon.padding_right=2
  label.padding_left=5
  label.padding_right=5
  background.corner_radius=4
  background.height=19
  background.color=$ACCENT_COLOR
  align=center
)
sketchybar --default "${default[@]}"

# Left
source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# Right
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/brew.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
